$schema: http://json-schema.org/draft-07/schema#
description: snakemake configuration file
required:
- parameters
- data
properties:
  parameters: 
    type: object 
    properties:
      infile:
        type: string
        description:  Path or list of paths (absolute or relative) to the files needed to start the pipeline. Please refer to **3/ Entry steps** for necessary files
      queryName:
        type: string
        description:  Identifier of the reference sequence for steps outside of blast and positiveSelection
        default:  ""
      queryFile:
        type: string
        description:  Input file containing the gene sequence
        default:  ""
      blastdb:
        type: string
        description:  NCBI database on which the blast is to be performed (ex nr)
        default:  nr
      outdir:
        type: string
        description:  Output directory for all results
        default:  ""
      logfile:
        type: string
        description:  Path to a file where progress of the pipeline will be logged
        default:  ""
      evalue:
        type: number
        description:  E-value for Blast (default 10⁻⁴)
        default:  0.003
      mincov:
        type: integer
        description:  Coverage for Blast (default 50)
        default:  50
      percID:
        type: integer
        description:  Percentage of identity for Blast (default 70)
        default:  70
      maxLen:
        type: string
        description:  Option for eliminating overly long sequences (default cutoff(3))
        default:  cutoff
      entryQuery:
        type: string
        description:  Can be used to limit the search on NCBI databases to certain set of species, to exclude others, etc.
        default:  ""
      APIKey:
        type: string
        description:  NCBI API key to increase Blast speed, obtainable from the NCBI
        default:  ""
      phymlOpt:
        type: string
        description:  Options for running PhyML
                      Input the command in the same way you would to run PhyML yourself in the following manner phyml -i ALN [the rest of your options]
                      For example, to run PhyML with a GTR model with 100 bootstraps, the option would be phymlOpt:phyml -i ALN -m GTR -b 100
                      Please be aware that PhyML will run even if your options are wrong, but with its own default parameters
        default:  ""
      sptree:
        type: string
        description:  Path to the species tree for the detection of duplication events and ortholog group assignment
                      Species names must be formated as speSpe or speSpeSpe (ex homSap, gorGorGor)
        default:  ""
      duplication:
        type: boolean
        description:  Option for the identification of duplication events (default False)
        default:  True
      LBopt:
        type: string
        description:  Option for Long Branch separation (default = cutoff(50))
                      IQR or cutoff, factor can be put after in parenthesis (ex = cutoff(50))
                      EXPERIMENTAL
        default:  cutoff
      nbspecies:
        type: integer
        description:  Minimum number of species for assignment to an ortholog group (default = 8)
        default:  8
      recombination:
        type: boolean
        description:  Option for the detection of recombination events (default = False)
        default:  False
      remote:
        type: boolean
        description:  Determines if Blast is performed against NCBI databases (default = True)
        default: False
      step:
        type: string
        description:  Step at which to enter the pipeline (default = blast)
                      Please refer to 3/ Entry steps for names and necessary files
        default: blast
      positiveSelection:
        type: boolean
        description:  Option for the detection of positive selection (default = False)
        default: False
      alnfile:
        type: string
        description: If alignment file given in infile, the file path will be stored in this variable  
        default: ""
      treefile:
        type: string
        description: If tree file given in infile, the file path will be stored in this variable 
        default: ""
      alnformat:
        type: string
        description: Format of the alignement file 
        default: Fasta
      basename:
        type: string
        description: Identifier of the query 
        default: ""
      hyphySeuil:
        type: number
        description:  P-value for Hyphy methods (BUSTED/MEME) (Pond *et al.*, 2005) (default = 0.1)
        default: 0.05
      busted:
        type: boolean
        description:  Option for using the Hyphy method BUSTED (Murrel *et al.*, 2015) (default = False)
        default: False
      meme:
        type: boolean
        description:  Option for using the Hyphy method BUSTED (Murrel *et al.*, 2015) (default = False)
        default: False
      models:
        type: string
        description:  Models to be computed by BIO++ (Gueguen *et al.*, 2013) and/or PAML (Yang, 2007)
                      Implemented models = M0, M1, M2, M7, M8, M8a, DFP07, DFP07_0
                      Must be comma separated (ex = M0,M1,M2)
                      Rate distribution are either Constant ou Gamma(n=4)
                      Default is Gamma, and explicit rate distribution are available through "_C" or "_G" suffixes to model names (ex = M0_C, M0_G)
        default: ""
      paml:
        type: boolean
        description:  Option for using paml for the detection of sites under positive selection (default = False)
        default: False
      bppml:
        type: [boolean, string]
        description:  Option for using BIO++ for the detection of sites under positive selection
                      If True, parameter file will be automatically generated
                      Can be used to indicate the path to a BIO++ parameter file
        default: True
      mixedlikelihood:
        type: [boolean, string]
        description:  Same as previously, but for extracting results from the results computed from bppml
        default: True
      opb:
        type: boolean
        description:  Option for using BIO++ for the detection of branches under positive selection
                      If True, parameter file will be automatically generated
                      Positive selection on each is assessed through LRT M2 vs M1 model in bio++.
                      Parameters different from omega are shared between all branches.
        default: False
      gnh:
        type: boolean
        description:  Pre-existing option before rewriting the pipeline, the definition was not found 
        default: False
      debug:
        type: boolean
        description:  Will enter verbose/debug mode
        default: False
      align_codon:
        type: array
        description:  Defines which codon aligner to use.
        default: ["macse"]
      align_nt :
        type : boolean
        description:  Defines wether or not to use mafft nucleotide alignment before the codon aligner
        default : True

    required:
      - infile 
    additionalProperties: False

  data: 
    type: object 
    properties:
      queryFile:
        type: string
        description:  Input file containing the gene sequence
      o:
        type: string
        description:  Output directory for all results
        default: workflow/results/
      logger:
        type: string
        description:  Path to a file where progress of the pipeline will be logged
      db:
        type: string
        description:  NCBI database on which the blast is to be performed (ex = nr)
      geneName: 
        type: string
        description:  Path to cluster hostfile if needed for mpi process
        default: ""
      sequence: 
        type: string
        description:  Path to cluster hostfile if needed for mpi process
        default: ""
      blastRes: 
        type: string
        description:  Path of the blast results
        default: ""
      lBlastRes: 
        type: array
        description:  Blast results in list format
      sptree: 
        type: string
        description:  Path to the species tree for the detection of duplication events and ortholog group assignment
                      Species names must be formated as speSpe or speSpeSpe (ex homSap, gorGorGor)
      ORFs: 
        type: string
        description:  Path of the ORFs step results 
        default: ""
      aln: 
        type: string
        description:   Path of the alignement results
      tree: 
        type: string
        description:  Path of the tree results
      queryName:
        type: string
        description:  Identifier of the reference sequence for steps outside of blast and positiveSelection
        default: ""
      alnFormat:
        type: string
        description:  Format of the alignement file 
        default: Format
      baseName:
        type: string
        description:  Identifier of the query 
        default: ""
      firstStep:
        type: string 
        description:  Entry step of the pipeline. Choose between blast, extraction, fasta, orf, alignement, tree, duplication, recombination, positiveSelection.
        default: "blast"
      dAlTree:
        type: object
        default: {}
        description:  Contains the correspondance between an alignment and its resulting species tree.
    additionalProperties: True


